### ISSUE TITLE
Returns UTF-8 for Cyrillic text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [UniversalCharsetDetector/ude#6]
```
What steps will reproduce the problem?
1. Define Cyrillic text, "Это пример кириллического 
текста".
2. Feed the CharsetDetector with stream to this text.
3. Result charset is "UTF-8" with Confidence 1.0

What is the expected output? 
Charset is koi-8

What do you see instead?
UTF-8

What version of the product are you using? 
Ude, C# port 

On what operating system?
Windows 7/8, x64

```

Original issue reported on code.google.com by `cached.b...@gmail.com` on 8 Dec 2012 at 8:19

**Comment by 304NotModified** [comment]
![image](https://cloud.githubusercontent.com/assets/5808377/11446404/bb1053e2-9536-11e5-968f-853d3ef814c9.png)

**Comment by 304NotModified** [comment]
This is tested with KOI8-R

**Comment by 304NotModified** [comment]
This just works. 

![image](https://cloud.githubusercontent.com/assets/5808377/11446457/783dee5c-9537-11e5-9dcf-aa36c13ded63.png)

![image](https://cloud.githubusercontent.com/assets/5808377/11446452/6fa4b136-9537-11e5-8f02-1c88731bc85d.png)

**Comment by 304NotModified** [comment]
See also https://github.com/errepi/ude/issues/6
